<footer>
<hr />
<p id="copyright">Автор &copy; 2004-2020 <a
href="mailto:Georgi%20Sotirov%20%3Cgdsotirov@gmail.com%3E">Георги Д. Сотиров</a>
<br />Всички права запазени</p>

<map id="conformancebar" name="conformancebar">
<p>
<!-- Valid HTML 5.0 -->
<a href="https://validator.w3.org/check?uri=referer" hreflang="en">
<img alt="[Икона Валиден HTML 5.0]" height="31" src="/img/valid-html5" title="Валиден HTML 5.0!" width="88" /></a>
<!-- Valid CSS -->
<a href="https://jigsaw.w3.org/css-validator/check/referer" hreflang="en">
<img alt="[Икона Валиден CSS]" height="31" src="/img/valid-css" title="Валиден CSS!" width="88" /></a>
<?php
  if ( isset($footer_atom_feed) ) {
?>
<!-- Valid Atom 1.0 -->
<a href="https://validator.w3.org/feed/check.cgi?url=<?php echo $footer_atom_feed ?>">
<img alt="[Валиден Atom 1.0]" height="31" src="/img/valid-atom" title="Проверете моята Atom емисия" width="88" /></a>
<?php
  }
?>
<?php
  if ( isset($footer_rss_feed) ) {
?>
<!-- Valid RSS 2.0 -->
<a href="https://validator.w3.org/feed/check.cgi?url=<?php echo $footer_rss_feed ?>">
<img alt="[Валиден RSS]" height="31" src="/img/valid-rss" title="Проверете моята RSS емисия" width="88" /></a>
<?php
  }
?>
<!-- WAI WCAG Conformance -->
<a href="https://www.w3.org/WAI/WCAG1AA-Conformance" hreflang="en">
<img alt="[Икона за съответствие с ниво двойно А]"
height="31" src="/img/wai-wcag-1.0-2a" title="Обяснение на съотвестстие със ниво двойно А" width="88" /></a>
<!-- UTF-8 Encoded -->
<a href="https://www.unicode.org/" hreflang="en">
<img alt="[Икона Кодирано в UTF-8]" height="31" src="/img/unicode" title="Кодирано в UTF-8!" width="88" /></a>
</p>
</map>

<map id="poweredbybar" name="poweredbybar">
<p><a href="https://www.kernel.org/" hreflang="en">
<img alt="[Задвижван от Linux]" height="31" src="/img/linux_pb" title="Задвижван от Linux" width="88" /></a>
<a href="https://www.apache.org/" hreflang="en">
<img alt="[Задвижван от Apache]" height="31" src="/img/apache_pb" title="Задвижван от Apache" width="88" /></a>
<a href="https://www.mysql.com/" hreflang="en">
<img alt="[Задвижван от MySQL]" height="31" src="/img/mysql_pb" title="Задвижван от MySQL" width="88" /></a>
<a href="https://www.php.net/" hreflang="en">
<img alt="[Задвижван от PHP]" height="31" src="/img/php_pb" title="Задвижван от PHP" width="88" /></a>
</p>
</map>

<p class="generated">Страницата е създадена: <?php echo date("Y-m-d H:i:s T"); ?></p>
</footer>

