<?php
  $I18N_LANG = 'en';
  include 'sysutil.php';
  include '../news.php.inc';
  $domain = "sotirov-bg.net";
?>
<!DOCTYPE html>

<html lang="en">

<head>
<meta charset="utf-8">
<title>Welcome to Sotirov-BG.Net</title>
<meta name="author" content="Georgi D. Sotirov, gdsotirov@gmail.com">
<meta name="description" content="Sotirov-BG.Net - the home server of Georgi Sotirov">
<meta name="keywords" content="Georgi Sotirov, Sotirov, server, projects, pages">
<meta name="robots" content="INDEX, FOLLOW">
<meta name="robots" content="ARCHIVE">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="icon" href="img/sotirov_net">
<link rel="shortcut icon" href="img/sotirov_net">
<link rel="stylesheet" href="style/default.css" media="screen, print"
      title="Default" type="text/css">
<link rel="stylesheet" href="style/speech.css" media="all"
      title="Default" type="text/css">
<link rel="alternate" type="text/html" href="index.bg" hreflang="bg" lang="bg"
      title="Sotirov-BG.Net - Домашният сървър на Георги Сотиров">
<link rel="alternate" type="text/html" href="index.en" hreflang="en" lang="en"
      title="Sotirov-BG.Net - The home server of Georgi Sotirov">
<link rel="alternate" href="news/feed.en?f=rss&amp;v=2.0" hreflang="en"
      lang="en" title="Sotirov-BG.Net News (RSS 2.0)"
      type="application/rss+xml">
<link rel="alternate" href="news/feed.en?f=atom" hreflang="en" lang="en"
      title="Sotirov-BG.Net News (Atom)" type="application/atom+xml">
</head>

<body>

<header>
<h1>Welcome to Sotirov-BG.Net</h1>
<p class="align-center">
<a href="https://translate.google.com/translate?sl=bg&tl=en&u=www.bgkoleda.bg"
target="_blank"><img alt="Bulgarian Christmas Banner" height="90" width="728"
src="img/bgkoleda" title="Bulgarian Christmas - Give hope to a child in need">
</a></p>
</header>

<nav id="Main">
<ul>
<li><a href="#news" hreflang="en">News</a></li>
<li><a href="#about" hreflang="en">About</a></li>
<li><a href="#avail" hreflang="en">Availability</a></li>
<li><a href="#content" hreflang="en">Content</a></li>
<li><a href="/iss.en" hreflang="en">
<abbr title="Iformation, Status, Statistics">ISS</abbr></a></li>
<li><a href="#copyright" hreflang="en">Copyright</a></li>
</ul>
<ul>
<li><a href="index.bg" hreflang="bg" lang="bg">Български</a></li>
</ul>
</nav>

<section>
<h2 id="news">News</h2>
<?php
  if ( $news_c = mysqli_connect($news_host, $news_user, $news_pass) ) {
    if ( mysqli_select_db($news_c, $news_db) ) {
      $query = "SELECT id, title, CONVERT_TZ(posted, 'SYSTEM', 'UTC') posted";
      $query .= " FROM news WHERE posted IS NOT NULL";
      $query .= " ORDER BY posted DESC";
      $query .= " LIMIT 10";
      $res = mysqli_query($news_c, $query);
      if ( mysqli_num_rows($res) > 0 ) {
        print("<p class=\"text_p\">Last ten news headers.</p>\n");
        print("<ul class=\"Last10\">\n");
        while ( $news = mysqli_fetch_array($res, MYSQLI_ASSOC) ) {
          print("<li><b>".$news['posted']."&nbsp;");
          print("<abbr title=\"Coordinated Universal Time\">UTC</abbr>");
          print("</b>&nbsp;<a ");
          print("href=\"/news/index.en?id=".$news['id']."\" hreflang=\"en\">");
          $title = preg_replace('/<[^<]+>/', '', $news['title']);
          print("$title</a></li>\n");
        }
        print("</ul>\n");
      }
      else {
        print("<p class=\"error\">News currently not available.</p>\n");
      }
      mysqli_free_result($res);
    }
    else {
      print("<p class=\"error\">News currently not available.</p>\n");
    }
    mysqli_close($news_c);
  }
  else {
    print("<p class=\"error\">News currently not available.</p>\n");
  }
?>
<nav id="News">
<ul>
<li><a href="news/index.en">Archive</a></li>
<li><img alt="Feed:" height="16" src="/icons/feed" width="16">&nbsp;<a
href="news/feed.en?f=atom" hreflang="en">Atom feed</a></li>
<li><img alt="Feed:" height="16" src="/icons/feed" width="16">&nbsp;<a
href="news/feed.en?f=rss&amp;v=2.0" hreflang="en"><abbr
title="Really Simple Syndication">RSS</abbr>&nbsp;feed</a></li>
</ul>
</nav>
</section>

<section>
<h2 id="about">About</h2>
<p class="text_p">This is the home server of <a
href="mailto:Georgi%20Sotirov%20%3Cgdsotirov@gmail.com%3E">Georgi Sotirov</a>.
Here you can find the most recent and actual information
about me, to view and use the things that I made and in general to get familiar
with my abilities. Please, note that all of the content on this server is
currently under <strong>constant
development</strong>.</p>
<p class="text_p">All pages on this server conform to the public
standards of <a href="https://www.w3.org/" hreflang="en"><abbr
title="World Wide Web Consortium">W3C</abbr></a>
and are created thus to be as accessible as possible
for a better and more quality Internet experience.</p>
</section>

<section>
<h2 id="avail">Availability</h2>
<p class="text_p">This server have on its disposal a high speed <abbr
title="Gigabit Passive Optical Network">PON</abbr> connection provided
by <a href="https://www.vivacom.bg/">Vivacom</a>.
The maximal (unwarranted) speeds are as follows:</p>
<ul class="inline">
<li>Worldwide - up to 300 <abbr title="Mega bits per second">Mb/s</abbr>
(37.5 <abbr title="Mega Bytes per second">MB/s</abbr>)</li>
<li>From Bulgaria - up to 300 <abbr title="Мega bits per second">Mb/s</abbr>
(37.5 <abbr title="Mega Bytes per second">МB/s</abbr>)</li>
</ul>
<p class="text_p">The server is equipped with uninterruptible power supply
(UPS), which in the best case could support it for up to 4 hours.</p>
</section>

<section>
<h2 id="content">Content</h2>
<article>
<h3>Hosted sites</h3>
<ul class="inline">
<li><a href="/~gsotirov/index.en" hreflang="en">Georgi's Personal Pages</a>
</li>
<li><a href="/~ibeleva/index.en" hreflang="en">Ivelina's Personal Pages</a>
</li>
<li><a href="https://slackpack.eu/" hreflang="en">SlackPack (Slackware
Packages)</a></li>
</ul>
</article>
<article>
<h3>Hosted applications</h3>
<ul class="inline">
<li><a href="/bugzilla/" hreflang="en">Sotirov-BG.Net Bugzilla</a> (with
Bulgarian localization)</li>
<li><a href="/apps/calc/icalc/index.en" hreflang="en">Interest calculator</a>
</li>
<li><a href="/apps/calc/mcalc/index.en" hreflang="en">Morgage calculator</a>
</li>
<li><a href="/apps/7klas/" hreflang="bg">Where after 7th grade?</a></li>
</ul>
</article>
<article>
<h3>Mirrors</h3>
<ul class="inline">
<li><a href="http://slackware.com/">Slackware</a> - all
releases with sources (by <a
href="ftp://<?php echo $domain ?>/pub/mirrors/slackware/"><abbr
title="File Transfer Protocol">FTP</abbr></a>, <a
href="https://ftp.<?php echo $domain ?>/pub/mirrors/slackware/"><abbr
title="Hypertext Transfer Protocol Secure">HTTPS</abbr></a>)
</li>
<li><a href="https://gnu.org/"><abbr
title="Gnu's Not Unix">GNU</abbr></a> - all (by <a
href="ftp://<?php echo $domain ?>/pub/mirrors/gnu/"><abbr
title="File Transfer Protocol">FTP</abbr></a>, <a
href="https://ftp.<?php echo $domain ?>/pub/mirrors/gnu/"><abbr
title="Hypertext Transfer Protocol Secure">HTTPS</abbr></a>)
</li>
</ul>
</article>
</section>

<?php
  $footer_atom_feed  = "https://".$_SERVER['SERVER_NAME'];
  $footer_atom_feed .= "/news/feed.en&amp;f=atom";
  $footer_rss_feed   = "https://".$_SERVER['SERVER_NAME'];
  $footer_rss_feed  .= "/news/feed.en?f=rss&amp;v=2.0";

  include 'footer.en.phtml'
?>
</body>

</html>

