<?php
  $I18N_LANG = 'bg';
  include 'sysutil.php';
  print("<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n");
  include '../news.php.inc';
  $domain = "sotirov-bg.net";
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="bg" lang="bg">

<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Добре дошли в Sotirov-BG.Net</title>
<meta name="author" content="Георги Д. Сотиров, gdsotirov@dir.bg" />
<meta name="description" content="Sotirov-BG.Net - домашният сървър на Георги Сотиров" />
<meta name="keywords" content="Георги Сотиров, Сотиров, сървър, проекти, страници" />
<meta name="robots" content="INDEX, FOLLOW" />
<meta name="robots" content="ARCHIVE" />
<meta name="CVS" content="$Id: index.bg.phtml,v 1.37 2019/04/02 17:41:22 gsotirov Exp $" />
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="icon" href="img/sotirov_net" />
<link rel="shortcut icon" href="img/sotirov_net" />
<link rel="stylesheet" href="style/default.css" media="screen, print" title="По подразбиране" type="text/css" />
<link rel="stylesheet" href="style/speech.css" media="aural" title="По подразбиране" type="text/css" />
<link rel="stylesheet" href="style/tty.css" media="tty" title="По подразбиране" type="text/css" />
<link rel="alternate" type="text/html" href="index.en" hreflang="en" lang="en" title="Sotirov-BG.Net - The home server of Georgi Sotirov" />
<link rel="alternate" type="text/html" href="index.bg" hreflang="bg" lang="bg" title="Sotirov-BG.Net - Домашният сървър на Георги Сотиров" />
<link rel="alternate" href="news/feed.bg?f=rss&amp;v=2.0" hreflang="bg" lang="bg" title="Новини от Sotirov-BG.Net (RSS 2.0)" type="application/rss+xml" />
<link rel="alternate" href="news/feed.bg?f=atom" hreflang="bg" lang="bg" title="Новини от Sotirov-BG.Net (Atom)" type="application/atom+xml" />
</head>

<body>
<div id="header">
<h1>Добре дошли в Sotirov-BG.Net</h1>
</div>

<div id="navigation">
<p class="navigation">
[&nbsp;<a href="#news" hreflang="bg">Новини</a>&nbsp;|&nbsp;<a
href="#about" hreflang="bg">Относно</a>&nbsp;|&nbsp;<a
href="#avail" hreflang="bg">Достъпност</a>&nbsp;|&nbsp;<a
href="#content" hreflang="bg">Съдържание</a>&nbsp;|&nbsp;<a
href="/iss.bg" hreflang="bg"><abbr title="Информация, Състояние, Статистики">ИСС</abbr></a>&nbsp;|&nbsp;<a
href="#copyright" hreflang="bg">Авторски права</a>&nbsp;]
<br />
[&nbsp;<a href="index.en" hreflang="en" lang="en">English</a>&nbsp;]
</p>
</div>

<div id="news">
<h2>Новини</h2>
<p><?php
  if ( $news_c = mysql_connect($news_host, $news_user, $news_pass) ) {
    if ( mysql_select_db($news_db, $news_c) ) {
      $query = "SELECT id, title, posted";
      $query .= " FROM news_bg WHERE posted <> '0000-00-00 00:00:00'";
      $query .= " ORDER BY posted DESC";
      $query .= " LIMIT 10";
      $res = mysql_query($query, $news_c);
      if ( mysql_num_rows($res) > 0 ) {
        print("Заглавия на 10-те последни новини.<br/><br/>\n");
        while ( $news = mysql_fetch_array($res, MYSQL_ASSOC) ) {
          print("<b>".$news['posted']."&nbsp;");
          print("<abbr lang=\"en\" title=\"Eastern European Time\">EET</abbr></b>&nbsp;");
          print("<a href=\"/news/index.bg?id=".$news['id']."\" hreflang=\"bg\">");
          $title = preg_replace('/<[^<]+>/', '', $news['title']);
          print("$title</a><br />\n");
        }
      }
      else
        print("Новините не са достъпни в момента.\n");
      mysql_free_result($res);
    }
    else
      print("Новините не са достъпни в момента.\n");
    mysql_close($news_c);
  }
  else
    print("Новините не са достъпни в момента.\n");
?></p>
<p>
<a href="news/index.bg">Архив</a>&nbsp;|&nbsp;
<img alt="Емисия:" longdesc="http://feedicons.com/" src="/icons/feed" />&nbsp;
<a href="news/feed.bg?f=atom" hreflang="bg">Atom емисия</a>&nbsp;|&nbsp;
<img alt="Емисия:" longdesc="http://feedicons.com/" src="/icons/feed" />&nbsp;
<a href="news/feed.bg?f=rss&amp;v=2.0" hreflang="bg"><acronym lang="en" title="Really Simple Syndication">RSS</acronym>&nbsp;емисия</a>
</p>
</div>

<div id="about">
<h2>Относно</h2>
<p class="text_p">Това е домашният сървър на <a href="mailto:Georgi%20Sotirov%20%3Cgdsotirov@dir.bg%3E">
Георги Сотиров</a>. Тук можете да намерите най-актуалната и точна информация
за мен, да разгледате и ползвате нещата които съм направил и като цяло да се
запознаете с моите възможности. Моля, имайте в предвид, че цялото съдържание
намиращо се на този сървър в момента е под <strong>постоянна
разработка</strong>.</p>
<p class="text_p">Всички станици на този сървър са издържани в публичните
стандарти на <a href="http://www.w3.org/" hreflang="en"><abbr title="World Wide Web Consortium - Консорциум на Световната Мрежа">W3C</abbr></a>
и са създадени така, че да са възможно
най-достъпни за едно по-добро и по-качествено Интернет изживяване.</p>
</div>

<div id="avail">
<h2>Достъпност</h2>
<p class="text_p">Този сървър разполага със висока по скорост <abbr
title="Local Area Network" lang="en">LAN</abbr> връзка. Максималните негарантирани скорости
са както следва:</p>
<ul class="inline">
<li>за целия свят - до 50 <abbr title="Mega бита за секунда">Mбзс</abbr> (6,25 <abbr title="Мега Байта за секунда">МБзс</abbr>)</li>
<li>от България - до 100 <abbr title="Мега бита за секунда">Мбзс</abbr> (12,5 <abbr title="Мега Байта за секунда">МБзс</abbr>)</li>
</ul>
<p class="text_p">Сървъра е екипиран с непрекъсваемо токозахранване, което в
най-добрия случай може да го поддържа до 30 минути.</p>
</div>

<div id="content">
<h2>Съдържание</h2>
<h3>Стопанисвани страници</h3>
<ul class="inline">
<li><a href="/~gsotirov/index.bg" hreflang="bg">Лични страници на Георги</a></li>
<li><a href="/~ibeleva/index.bg" hreflang="bg">Лични страници на Ивелина</a></li>
<li><a href="/slackpack/" hreflang="bg">SlackPack (Пакети за Slackware)</a></li>
</ul>

<h3>Стопанисвани приложения</h3>
<ul class="inline">
<li><a href="/bugzilla/" hreflang="en">Sotirov-BG.Net Bugzilla</a></li>
<li><a href="/viewvc/" hreflang="en">Sotirov-BG.Net CVS хранилище</a></li>
<li><a href="/apps/calc/mcalc/index.bg" hreflang="bg">Ипотечен калкулатор</a></li>
<li><a href="/apps/calc/icalc/index.bg" hreflang="bg">Лихвен калкулатор</a></li>
</ul>

<h3>Огледала</h3>
<ul class="inline">
<li><a hreflang="en" href="http://slackware.com/">Slackware</a> - всички версии с изходен код (по
<a href="ftp://<?php echo $domain ?>/pub/mirrors/slackware/">
  <abbr lang="en" title="File Transfer Protocol">FTP</abbr></a>,
<a href="http://ftp.<?php echo $domain ?>/pub/mirrors/slackware/">
  <abbr lang="en" title="Hypertext Transfer Protocol">HTTP</abbr></a>,
<a href="https://ftp.<?php echo $domain ?>/pub/mirrors/slackware/">
  <abbr lang="en" title="Hypertext Transfer Protocol Secure">HTTPS</abbr></a>)
</li>
<li><a hreflang="en" href="http://gnu.org/"><abbr title="Gnu's Not Unix">GNU</abbr></a> - всичко (по
<a href="ftp://<?php echo $domain ?>/pub/mirrors/gnu/">
  <abbr lang="en" title="File Transfer Protocol">FTP</abbr></a>,
<a href="http://ftp.<?php echo $domain ?>/pub/mirrors/gnu/">
  <abbr lang="en" title="Hypertext Transfer Protocol">HTTP</abbr></a>,
<a href="https://ftp.<?php echo $domain ?>/pub/mirrors/gnu/">
  <abbr lang="en" title="Hypertext Transfer Protocol Secure">HTTPS</abbr></a>)
</li>
</ul>
</div>

<div id="copyright">
<hr />
<p>Автор &copy; 2004-2018 <a href="mailto:Georgi%20Sotirov%20%3Cgdsotirov@dir.bg%3E">Георги
Д. Сотиров</a><br />Всички права запазени</p>
</div>

<div id="conformance">
<map id="conformancebar">
<p>
<!-- Valid XHTML 1.0 -->
<a href="http://validator.w3.org/check?uri=referer" hreflang="en">
<img alt="[Икона Валиден XHTML 1.0]" height="31" longdesc="http://validator.w3.org/" src="img/valid-xhtml" title="Валиден XHTML 1.0!" width="88" /></a>
<!-- Valid CSS -->
<a href="http://jigsaw.w3.org/css-validator/check/referer" hreflang="en">
<img alt="[Икона Валиден CSS]" height="31" longdesc="http://jigsaw.w3.org/" src="img/valid-css" title="Валиден CSS!" width="88" /></a>
<!-- WAI WCAG Conformance -->
<a href="http://www.w3.org/WAI/WCAG1AA-Conformance" hreflang="en">
<img alt="[Икона за съответствие с ниво двойно А]"
height="31" longdesc="http://www.w3.org/WAI/" src="img/wai-wcag-1.0-2a" title="Обяснение на съотвестстие със ниво двойно А" width="88" /></a>
<!-- UTF-8 Encoded -->
<a href="http://www.unicode.org/" hreflang="en">
<img alt="[Икона Кодирано в UTF-8]" height="31" longdesc="http://www.unicode.org/" src="img/unicode" title="Кодирано в UTF-8!" width="88" /></a>
</p></map>
</div>

<div id="poweredby">
<map id="poweredbybar">
<p><a href="https://www.kernel.org/" hreflang="en">
<img alt="[Работи с мощта на Linux]" height="31" longdesc="https://www.kernel.org/" src="img/linux_pb" title="Работи с мощта на Linux" width="88" /></a>
<a href="http://www.apache.org/" hreflang="en">
<img alt="[Работи с мощта на Apache]" height="31" longdesc="http://www.apache.org/" src="img/apache_pb" title="Работи с мощта на Apache" width="88" /></a>
<a href="http://www.mysql.com/" hreflang="en">
<img alt="[Работи с MySQL]" height="31" longdesc="http://www.mysql.com/" src="img/mysql_pb" title="Работи с MySQL" width="88" /></a>
<a href="http://www.php.net/" hreflang="en">
<img alt="[Работи с мощта на PHP]" height="31" longdesc="http://www.php.net/" src="img/php_pb" title="Работи с мощта на PHP" width="88" /></a>
</p></map>
</div>

</body>
</html>

