<?php
  $I18N_LANG = 'en';
  include 'sysutil.php';
  print("<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n");
  include '../news.php.inc';
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Welcome to Sotirov-BG.Net</title>
<meta name="author" content="Georgi D. Sotirov, gdsotirov@dir.bg" />
<meta name="description" content="Sotirov-BG.Net - the home server of Georgi Sotirov" />
<meta name="keywords" content="Georgi Sotirov, Sotirov, server, projects, pages" />
<meta name="robots" content="INDEX, FOLLOW" />
<meta name="robots" content="ARCHIVE" />
<meta name="CVS" content="$Id: index.en.phtml,v 1.28 2007/11/14 21:09:04 gsotirov Exp $" />
<link rel="icon" href="img/sotirov_net" />
<link rel="shortcut icon" href="img/sotirov_net" />
<link rel="stylesheet" media="screen, print" title="Default" type="text/css" href="style/default.css" />
<link rel="stylesheet" media="aural" title="Default" type="text/css" href="style/speech.css" />
<link rel="stylesheet" media="tty" title="Default" type="text/css" href="style/tty.css" />
<link rel="alternate" type="text/html" href="index.bg.phtml" hreflang="bg" lang="bg" title="Sotirov-BG.Net - Домашният сървър на Георги Сотиров" />
<link rel="alternate" href="news/feed?f=rss&amp;v=2.0" title="Sotirov-BG.Net News (RSS 2.0)" type="application/rss+xml" />
<link rel="alternate" href="news/feed?f=atom" title="Sotirov-BG.Net News (Atom)" type="application/atom+xml" />
</head>

<body>
<div id="header">
<h1>Welcome to Sotirov-BG.Net</h1>
</div>

<div id="nosoftwarepatents">
<p class="align-center">
<a href="http://www.nosoftwarepatents.com/"><img alt="No software patents!" height="90"
title="No software patents!" src="img/nosoftwarepatents" width="390" /></a></p>
</div>

<div id="navigation">
<p class="navigation">
[&nbsp;
<a href="#news">News</a>&nbsp;|&nbsp;<a
href="#about">About</a>&nbsp;|&nbsp;<a
href="#avail">Availability</a>&nbsp;|&nbsp;<a
href="#content">Content</a>&nbsp;|&nbsp;<a
href="iss"><abbr title="Iformation, Status, Statistics">ISS</abbr></a>&nbsp;|&nbsp;<a
href="#copyright">Copyright</a>&nbsp;]
<br />
[&nbsp;<a href="index.bg.phtml" hreflang="bg" lang="bg">Български</a>&nbsp;]
</p>
</div>

<div id="news">
<h2>News</h2>
<p><?php
  if ( $news_c = mysql_connect($news_host, $news_user, $news_pass) ) {
    if ( mysql_select_db($news_db, $news_c) ) {
      $query = "SELECT id, title, posted";
      $query .= " FROM news WHERE posted <> '0000-00-00 00:00:00'";
      $query .= " ORDER BY posted DESC";
      $query .= " LIMIT 10";
      $res = mysql_query($query, $news_c);
      if ( mysql_num_rows($res) > 0 ) {
        print("<p>Last ten news headers.</p>\n");
        while ( $news = mysql_fetch_array($res, MYSQL_ASSOC) ) {
          print("<b>".$news['posted']."&nbsp;");
          print("<abbr title=\"Eastern European Time\">EET</abbr></b>&nbsp;");
          print("<a href=\"news?id=".$news['id']."\">");
          $title = preg_replace('/<[^<]+>/', '', $news['title']);
          print("$title</a><br />\n");
        }
      }
      else
        print("News currently not available.\n");
      mysql_free_result($res);
    }
    else
      print("News currently not available.\n");
    mysql_close($news_c);
  }
  else
    print("News currently not available.\n");
?></p>
<p>
<a href="news/">Archive</a>&nbsp;|&nbsp;<img alt="Feed:" longdesc="http://feedicons.com/" src="/icons/feed" />&nbsp;<a href="news/feed?f=atom">Atom feed</a>&nbsp;|&nbsp;<img alt="Feed:" longdesc="http://feedicons.com/" src="/icons/feed" />&nbsp;<a
href="news/feed?f=rss&amp;v=2.0"><acronym title="Really Simple Syndication">RSS</acronym>&nbsp;feed</a></p>
</div>

<div id="about">
<h2>About</h2>
<p class="text_p">This is the home server of <a href="mailto:Georgi%20Sotirov%20%3Cgdsotirov@dir.bg%3E">
Georgi Sotirov</a>. Here you can find the most recent and actual information
about me, to view and use the things that I made and in general to get familiar
with my posibilities. Please, note that all of the content on this server is
currentlly under <strong>constant development</strong>.</p>
<p class="text_p">All pages on this server conform to the public standards of
<a href="http://www.w3.org/"><abbr title="World Wide Web Consortium">W3C</abbr></a>
and are created thus to be as accessable as possible for a better and more
quality Internet experience.</p>
</div>

<div id="avail">
<h2>Availability</h2>
<p class="text_p">Тhis server have on its disposal a medium speed dial-up
conection. The speeds are as follows:</p>
<ul class="inline">
<li>Worldwide - up to 8 <abbr title="Mega bits per second">Mbps</abbr> (1 <abbr title="Mega Bytes per second">MBps</abbr>)</li>
<li>From Bulgaria - up to 40 <abbr title="Мega bits per second">Mbps</abbr> (5 <abbr title="Mega Bytes per second">МBps</abbr>)</li>
</ul>
<p class="text_p">The server is equipped with uninterruptible power supply,
which in in the best case could support it for up to 40 minutes.</p>
</div>

<div id="content">
<h2>Content</h2>
<h3>Hosted sites</h3>
<ul>
<li><a href="~gsotirov/">Georgi's Personal Pages</a></li>
<li><a href="~ibeleva/">Ivelina's Personal Pages</a></li>
<li><a href="slackpack/">SlackPack (Georgi Sotirov's Slackware Packages)</a></li>
<li><a href="~ibeleva/wedding/" hreflang="bg">Sotirov's Wedding Album</a></li>
</ul>

<h3>Hosted applications</h3>
<ul class="inline">
<li><a href="bugzilla/">Sotirov-BG.Net Bugzilla</a></li>
<li><a href="viewvc/">Sotirov-BG.Net CVS Repository</a></li>
<li><a href="apps/calc/mcalc/" hreflang="en">Morgage calculator</a></li>
<li><a href="apps/calc/icalc/" hreflang="en">Interest calculator</a></li>
</ul>
</div>

<div id="copyright">
<hr />
<p>Copyright &copy; 2004-2007 <a href="mailto:Georgi%20Sotirov%20%3Cgdsotirov@dir.bg%3E">Georgi
D. Sotirov</a><br />All right reserved</p>
</div>

<div id="conformance">
<map id="conformancebar">
<p>
<!-- Valid XHTML 1.0 -->
<a href="http://validator.w3.org/check?uri=referer" hreflang="en">
<img alt="[Valid XHTML 1.0 icon]" height="31" longdesc="http://validator.w3.org/" src="img/valid-xhtml" title="Valid XHTML 1.0!" width="88" /></a>
<!-- Valid CSS -->
<a href="http://jigsaw.w3.org/css-validator/check/referer" hreflang="en">
<img alt="[Valid CSS icon]" height="31" longdesc="http://jigsaw.w3.org/" src="img/valid-css" title="Valid CSS!" width="88" /></a>
<!-- WAI WCAG Conformance -->
<a href="http://www.w3.org/WAI/WCAG1AA-Conformance">
<img alt="[Level Double-A conformance icon]"
height="31" longdesc="http://www.w3.org/WAI/" src="img/wai-wcag-1.0-2a" title="Explanation of Level Double-A Conformance" width="88" /></a>
<!-- UTF-8 Encoded -->
<a href="http://www.unicode.org/" hreflang="en">
<img alt="[Encoded in UTF-8 icon]" height="31" longdesc="http://www.unicode.org/" src="img/unicode" title="Encoded in UTF-8!" width="88" /></a>
</p></map>
</div>

<div id="poweredby">
<map id="poweredbybar">
<p><a href="http://www.kernel.org/" hreflang="en">
<img alt="[Powered by Linux]" height="31" longdesc="http://www.kernel.org/" src="img/linux_pb" title="Powered by Linux" width="88" /></a>
<a href="http://www.apache.org/" hreflang="en">
<img alt="[Powered by Apache]" height="31" longdesc="http://www.apache.org/" src="img/apache_pb" title="Powered by Apache" width="88" /></a>
<a href="http://www.mysql.com/" hreflang="en">
<img alt="[Works with MySQL]" height="31" longdesc="http://www.mysql.com/" src="img/mysql_pb" title="Works with MySQL" width="88" /></a>
<a href="http://www.php.net/" hreflang="en">
<img alt="[Powered by PHP]" height="31" longdesc="http://www.php.net/" src="img/php_pb" title="Powered by PHP" width="88" /></a>
</p></map>
</div>

</body>

</html>

