<?php
  $I18N_LANG = 'bg';
  include 'sysutil.php';
  print("<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n");
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="bg" lang="bg">

<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Sotirov-BG.Net - Информация, Състояние, Статистики</title>
<meta name="author" content="Георги Д. Сотиров, gdsotirov@dir.bg" />
<meta name="description" content="Sotirov-BG.Net - Информация за сървъра" />
<meta name="keywords" content="Георги Сотиров, Сотиров, сървър, проекти, страници" />
<meta name="robots" content="NOINDEX, FOLLOW" />
<meta name="robots" content="NOARCHIVE" />
<meta name="CVS" content="$Id: iss.bg.phtml,v 1.14 2006/11/13 21:49:44 gsotirov Exp $" />
<link rel="icon" href="img/sotirov_net" />
<link rel="shortcut icon" href="img/sotirov_net" />
<link rel="stylesheet" media="screen, print" title="По подразбиране" type="text/css" href="style/default.css" />
<link rel="stylesheet" media="aural" title="По подразбиране" type="text/css" href="style/speech.css" />
<link rel="stylesheet" media="tty" title="По подразбиране" type="text/css" href="style/tty.css" />
<link rel="alternate" type="text/html" href="iss.bg.phtml" hreflang="en" lang="en" title="Sotirov.Net - Server information" />
<link rel="start" href="index" title="Начало" />
</head>

<body>
<div id="header">
<h1>Информация, състояние, статистики</h1>
</div>

<div id="navigation">
<p class="navigation">
[&nbsp;<a
href="/">Начална страница</a>&nbsp;|&nbsp;<a
href="iss.en.phtml" hreflang="en" lang="en">English</a>&nbsp;]
</p>
</div>

<p>Тази информация се предоставя главно с цел системно наблюдение.</p>

<div id="info_status_stats">
<div id="server_himself">
<img alt="Снимка на сървъра" id="server_pic" height="350" longdesc="img/server"
src="img/server" title="Самият сървър" width="320" /></div>
<div id="server_info_status_stats">
<h2>Обща информация</h2>
<pre><?php
  printf("<i><abbr title=\"Операционна система\">ОС</abbr></i>:          <span lang=\"en\">%s</span>\n", os_info());
  printf("<i>Ядро</i>:        <span lang=\"en\">%s</span>\n", kernel_info());
  printf("<i>Дистрибуция</i>: <span lang=\"en\">%s</span>\n", slack_ver());
  printf("<i>Архитектура</i>: <span lang=\"en\">%s</span>\n", mach_info());
  printf("<i>Процесор</i>:    <span lang=\"en\">%s</span>\n", cpu_info());
?>
</pre>
<h2>Състояние на сървъра</h2>
<pre><?php
  $sysup = sysup();
  printf("<i>Работещ от</i>:         %s\n", $sysup[0]);
  printf("<i>Време на работа</i>:    %s\n", $sysup[1]);
  printf("<i>Средно натоварване</i>: %s\n", loadavg());
  $meminfo = meminfo();
  printf("<i>Памет</i>:              %s\n", $meminfo[0]);
  printf("<i>Виртуална памет</i>:    %s\n", $meminfo[1]);
?>
</pre>
<h2>Използван капацитет</h2>
<!-- The bandwidth bar program is available at:
 http://www.kernel.org/pub/software/web/bwbar/ -->
<?php
  $bwbar = fopen("bwbar/bwbar.txt", "r");
  fscanf($bwbar, "%f %f %s", $cur_bw, $max_bw, $unit);
  fclose($bwbar);
?>
<p>Текущо <?php
  printf("%6.2f %s", $cur_bw, hr_bandw($unit));
?> от <?php printf("%6.2f %s", $max_bw, hr_bandw($unit));
?> използвани<br />
<img alt="Използван капацитет" height="6" longdesc="http://www.kernel.org/pub/software/web/bwbar/" src="bwbar/bwbar.png" width="602" />
</p>
<h2>Статистики</h2>
<ul>
<li><a href="stats/traffic/" hreflang="en">Трафик</a>&nbsp;<img alt="[парола]"
height="16" src="/img/lock" title="Изисква се удостоверяване" width="16" /></li>
<li><a href="stats/hotsanic/" hreflang="en">Системна статистика</a>&nbsp;<img
alt="[парола]" height="16" src="/img/lock" title="Изисква се удостоверяване"
width="16" /></li>
<li><a href="stats/awstats/awstats.pl?config=web">Web статистики</a>&nbsp;<img
alt="[парола]" height="16" src="/img/lock" title="Изисква се удостоверяване"
width="16" />, <a href="stats/awstats/awstats.pl?config=ftp"><abbr lang="en" title="File Transfer Protocl">FTP</abbr>&nbsp;статистики</a>&nbsp;<img
alt="[парола]" height="16" src="/img/lock" title="Изисква се удостоверяване"
width="16" /></li>
</ul>
</div>
</div>

<div id="conformance">
<hr />
<map id="conformancebar">
<p>
<!-- Valid XHTML 1.0 -->
<a href="http://validator.w3.org/check?uri=referer" hreflang="en">
<img alt="[Икона Валиден XHTML 1.0]" height="31" longdesc="http://validator.w3.org/" src="img/valid-xhtml" title="Валиден XHTML 1.0!" width="88" /></a>
<!-- Valid CSS -->
<a href="http://jigsaw.w3.org/css-validator/check/referer" hreflang="en">
<img alt="[Икона Валиден CSS]" height="31" longdesc="http://jigsaw.w3.org/" src="img/valid-css" title="Валиден CSS!" width="88" /></a>
<!-- WAI WCAG Conformance -->
<a href="http://www.w3.org/WAI/WCAG1AA-Conformance" hreflang="en">
<img alt="[Икона за съответствие с ниво двойно А]" height="31" longdesc="http://www.w3.org/WAI/" src="img/wai-wcag-1.0-2a" title="Обяснение на съотвестстие със ниво двойно А" width="88" /></a>
<a href="http://www.unicode.org/" hreflang="en">
<img alt="[Икона Кодирано в UTF-8]" height="31" longdesc="http://www.unicode.org/" src="img/unicode" title="Кодирано в UTF-8!" width="88" /></a>
</p></map>
</div>

<div id="poweredby">
<map id="poweredbybar">
<p><a href="http://www.kernel.org/" hreflang="en">
<img alt="[Работи с мощта на Linux]" height="31" longdesc="http://www.kernel.org/" src="img/linux_pb" title="Работи с мощта на Linux" width="88" /></a>
<a href="http://www.apache.org/" hreflang="en">
<img alt="[Работи с мощта на Apache]" height="31" longdesc="http://www.apache.org/" src="img/apache_pb" title="Работи с мощта на Apache" width="88" /></a>
<a href="http://www.php.net/" hreflang="en">
<img alt="[Работи с мощта на PHP]" height="31" longdesc="http://www.php.net/" src="img/php_pb" title="Работи с мощта на PHP" width="88" /></a>
</p></map>
</div>

<div id="generated">
<p>Страницата е създадена: <?php echo date("Y-m-d H:i:s T"); ?></p>
</div>

</body>
</html>
