<?php
  $I18N_LANG = 'bg';
  include 'sysutil.php';
?>
<!DOCTYPE html>

<html lang="bg">

<head>
<meta charset="utf-8">
<title>Sotirov-BG.Net - Информация, Състояние, Статистики</title>
<meta name="author" content="Георги Д. Сотиров, gdsotirov@gmail.com" />
<meta name="description" content="Sotirov-BG.Net - Информация за сървъра" />
<meta name="keywords" content="Георги Сотиров, Сотиров, сървър, проекти, страници" />
<meta name="robots" content="NOINDEX, FOLLOW" />
<meta name="robots" content="NOARCHIVE" />
<link rel="icon" href="img/sotirov_net" />
<link rel="shortcut icon" href="img/sotirov_net" />
<link rel="stylesheet" media="screen, print" title="По подразбиране" type="text/css" href="style/default.css" />
<link rel="stylesheet" media="speech" title="По подразбиране" type="text/css" href="style/speech.css" />
<link rel="alternate" type="text/html" href="iss.en" hreflang="en" lang="en" title="Sotirov.Net - Server information" />
<link rel="alternate" type="text/html" href="iss.bg" hreflang="bg" lang="bg" title="Sotirov.Net - Информация за сървъра" />
<link rel="start" href="index" title="Начало" />
</head>

<body>
<header>
<h1>Информация, състояние, статистики</h1>
</header>

<nav id="Main">
<ul>
<li><a href="/">Начална страница</a></li>
<li><a href="iss.en.phtml" hreflang="en" lang="en">English</a></li>
</ul>
</nav>

<section>
<h2>Информация, състояние и статистики на сървъра</h2>
<p class="text_p">Страницата предоставя обща информация и състояние на
сървъра. Статистиките са достъпни само за администратори.</p>
<div id="server_itself">
<img alt="Снимка на сървъра" id="server_pic"
src="img/server" title="Сървъра в шкафа (2-рата единица от горе)" width="480" />
</div>
<div id="server_info_status_stats">
<article>
<h3>Обща информация</h3>
<pre><?php
  printf("<i><abbr title=\"Операционна система\">ОС</abbr></i>:          <span lang=\"en\">%s</span>\n", os_info());
  printf("<i>Ядро</i>:        <span lang=\"en\">%s</span>\n", kernel_info());
  printf("<i>Дистрибуция</i>: <span lang=\"en\">%s</span>\n", slack_ver());
  printf("<i>Архитектура</i>: <span lang=\"en\">%s</span>\n", mach_info());
  printf("<i>Процесор</i>:    <span lang=\"en\">%s</span>\n", cpu_info());
?>
</pre>
</article>
<article>
<h3>Състояние на сървъра</h3>
<pre><?php
  $sysup = sysup();
  printf("<i>Работещ от</i>:         %s\n", $sysup[0]);
  printf("<i>Време на работа</i>:    %s\n", $sysup[1]);
  printf("<i>Захранване</i>:         %s\n", ups_power('mgeups'));
  printf("<i>Заряд батерия</i>:      %s %%\n", ups_charge('mgeups'));
  printf("<i>Средно натоварване</i>: %s\n", loadavg());

  $mi_arr = meminfo();

  $pm_free  = $mi_arr['MemFree'];
  $pm_total = $mi_arr['MemTotal'];
  $vm_free  = $mi_arr['SwapFree'];
  $vm_total = $mi_arr['SwapTotal'];

  printf("<i>Памет</i>:              %s\n",
         sprintf(i18n_msg('mem_msg'),
                 hr_mem($pm_free*1024),
                 hr_mem($pm_total*1024)));
  printf("<i>Виртуална памет</i>:    %s\n",
         sprintf(i18n_msg('mem_msg'),
                 hr_mem($vm_free*1024),
                 hr_mem($vm_total*1024)));
?>
</pre>
</article>
<article>
<h3>Използван капацитет</h3>
<!-- The bandwidth bar program is available at:
 https://www.kernel.org/pub/software/web/bwbar/ -->
<?php
  $bwbar = fopen("bwbar/bwbar.txt", "r");
  fscanf($bwbar, "%f %f %s", $cur_bw, $max_bw, $unit);
  fclose($bwbar);
?>
<p>Текущо <?php
  printf("%6.2f %s", $cur_bw, hr_bandw($unit));
?> от <?php printf("%6.2f %s", $max_bw, hr_bandw($unit));
?> използвани<br />
<img alt="Използван капацитет" height="6"
     src="bwbar/bwbar.png" width="400" />
</p>
</article>
<article>
<h3>Статистики</h3>
<ul>
<li><a href="stats/traffic/" hreflang="en">Трафик</a>&nbsp;<img alt="[парола]"
height="16" src="/img/lock" title="Изисква се удостоверяване" width="16" /></li>
<li><a href="stats/cacti/graph_view.php?action=tree" hreflang="en">Системна статистика</a>&nbsp;
<img alt="[парола]" height="16" src="/img/lock" title="Изисква се удостоверяване"
width="16" /></li>
<li><a href="stats/awstats/awstats.pl?config=web">Web статистики</a>&nbsp;<img
alt="[парола]" height="16" src="/img/lock" title="Изисква се удостоверяване"
width="16" />, <a href="stats/awstats/awstats.pl?config=ftp"><abbr lang="en" title="File Transfer Protocl">FTP</abbr>&nbsp;статистики</a>&nbsp;<img
alt="[парола]" height="16" src="/img/lock" title="Изисква се удостоверяване"
width="16" /></li>
</ul>
</article>
</div>
</section>

<?php
  include 'footer.bg.phtml'
?>
</body>

</html>

