<?php
  $I18N_LANG = 'en';
  include 'sysutil.php';
?>
<!DOCTYPE html>

<html lang="en">

<head>
<meta charset="utf-8">
<title>Sotirov-BG.Net - Information, Status, Statistics</title>
<meta name="author" content="Georgi D. Sotirov, gdsotirov@dir.bg" />
<meta name="description" content="Sotirov-BG.Net - Server information" />
<meta name="keywords" content="Georgi Sotirov, Sotirov, server, projects, pages" />
<meta name="robots" content="NOINDEX, FOLLOW" />
<meta name="robots" content="NOARCHIVE" />
<link rel="icon" href="img/sotirov_net" />
<link rel="shortcut icon" href="img/sotirov_net" />
<link rel="stylesheet" media="screen, print" title="Default" type="text/css" href="style/default.css" />
<link rel="stylesheet" media="speech" title="Default" type="text/css" href="style/speech.css" />
<link rel="alternate" type="text/html" href="iss.bg" hreflang="bg" lang="bg" title="Sotirov.Net - Информация за сървъра" />
<link rel="alternate" type="text/html" href="iss.en" hreflang="en" lang="en" title="Sotirov.Net - Server information" />
<link rel="start" href="index" title="Home" />
</head>

<body>
<header>
<h1>Information, Status, Statistics</h1>
</header>

<nav id="Main">
<ul>
<li><a href="/">Home</a></li>
<li><a href="iss.bg.phtml" hreflang="bg" lang="bg">Български</a></li>
</ul>
</nav>

<section>
<h2>Information, status and statistics for the server</h2>
<p class="text_p">This page provides general information and server
status. The statistics are available only to administrators.</p>
<div id="server_itself">
<img alt="Server picture" id="server_pic"
src="img/server" title="The server in the rack (2nd unit from top)" width="480" />
</div>
<div id="server_info_status_stats">
<article>
<h3>General info</h3>
<pre><?php
  printf("<i><abbr title=\"Operating System\">OS</abbr></i>:           %s\n", os_info());
  printf("<i>Kernel</i>:       %s\n", kernel_info());
  printf("<i>Distribution</i>: %s\n", slack_ver());
  printf("<i>Machine</i>:      %s\n", mach_info());
  printf("<i><abbr title=\"Central Processing Unit\">CPU</abbr></i>:          %s\n", cpu_info());
?>
</pre>
</article>
<article>
<h3>Server status</h3>
<pre><?php
  $sysup = sysup();
  printf("<i>Up since</i>:       %s\n", $sysup[0]);
  printf("<i>Up time</i>:        %s\n", $sysup[1]);
  printf("<i>Power</i>:          %s\n", ups_power('mgeups'));
  printf("<i>Battery charge</i>: %s %%\n", ups_charge('mgeups'));
  printf("<i>Load average</i>:   %s\n", loadavg());

  $mi_arr = meminfo();

  $pm_free  = $mi_arr['MemFree'];
  $pm_total = $mi_arr['MemTotal'];
  $vm_free  = $mi_arr['SwapFree'];
  $vm_total = $mi_arr['SwapTotal'];

  printf("<i>Memory</i>:         %s\n",
         sprintf(i18n_msg('mem_msg'),
                 hr_mem($pm_free*1024),
                 hr_mem($pm_total*1024)));
  printf("<i>Swap</i>:           %s\n",
         sprintf(i18n_msg('mem_msg'),
                 hr_mem($vm_free*1024),
                 hr_mem($vm_total*1024)));
?>
</pre>
</article>
<article>
<h3>Bandwith utilization</h3>
<!-- The bandwidth bar program is available at:
 https://www.kernel.org/pub/software/web/bwbar/ -->
<?php
  $bwbar = fopen("bwbar/bwbar.txt", "r");
  fscanf($bwbar, "%f %f %s", $cur_bw, $max_bw, $unit);
  fclose($bwbar);
?>
<p>Currently <?php
  printf("%6.2f %s", $cur_bw, hr_bandw($unit));
?> of <?php printf("%6.2f %s", $max_bw, hr_bandw($unit));
?> used<br />
<img alt="Използван капацитет" height="6"
     src="bwbar/bwbar.png" width="400" />
</p>
</article>
<article>
<h3>Statistics</h3>
<ul>
<li><a href="stats/traffic/">Traffic</a>&nbsp;<img alt="[auth]"
height="16" src="/img/lock" title="Login required" width="16" /></li>
<li><a href="stats/cacti/graph_view.php?action=tree">System statistics</a>&nbsp;
<img alt="[auth]" height="16" src="/img/lock" title="Login required"
width="16" /></li>
<li><a href="stats/awstats/awstats.pl?config=web">Web statistics</a>&nbsp;<img
alt="[парола]" height="16" src="/img/lock" title="Изисква се удостоверяване"
width="16" />, <a href="stats/awstats/awstats.pl?config=ftp"><abbr title="File Transfer Protocl">FTP</abbr>&nbsp;statistics</a>&nbsp;<img
alt="[парола]" height="16" src="/img/lock" title="Изисква се удостоверяване"
width="16" /></li>
</ul>
</article>
</div>
</section>

<footer>
<hr />
<map id="conformancebar" name="conformancebar">
<p>
<!-- Valid HTML 5.0 -->
<a href="https://validator.w3.org/check?uri=referer" hreflang="en">
<img alt="[Valid HTML 5.0 icon]" height="31" src="img/valid-html5" title="Valid HTML 5.0!" width="88" /></a>
<!-- Valid CSS -->
<a href="https://jigsaw.w3.org/css-validator/check/referer" hreflang="en">
<img alt="[Valid CSS icon]" height="31" src="img/valid-css" title="Valid CSS!" width="88" /></a>
<!-- WAI WCAG Conformance -->
<a href="https://www.w3.org/WAI/WCAG1AA-Conformance">
<img alt="[Level Double-A conformance icon]"
height="31" src="img/wai-wcag-1.0-2a" title="Explanation of Level Double-A Conformance" width="88" /></a>
<!-- UTF-8 Encoded -->
<a href="https://www.unicode.org/" hreflang="en">
<img alt="[Encoded in UTF-8 icon]" height="31" src="img/unicode" title="Encoded in UTF-8!" width="88" /></a>
</p>
</map>

<map id="poweredbybar" name="poweredbybar">
<p><a href="https://www.kernel.org/" hreflang="en">
<img alt="[Powered by Linux]" height="31" src="img/linux_pb" title="Powered by Linux" width="88" /></a>
<a href="https://www.apache.org/" hreflang="en">
<img alt="[Powered by Apache]" height="31" src="img/apache_pb" title="Powered by Apache" width="88" /></a>
<a href="https://php.net/" hreflang="en">
<img alt="[Powered by PHP]" height="31" src="img/php_pb" title="Powered by PHP" width="88" /></a>
</p>
</map>

<p class="generated">Page generated: <?php echo date("Y-m-d H:i:s T"); ?></p>
</footer>

</body>

</html>

