<?php
  $I18N_LANG = 'en';
  include 'sysutil.php';
  print("<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n");
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Sotirov.Net - Information, Status, Statistics</title>
<meta name="author" content="George D. Sotirov, gdsotirov@dir.bg" />
<meta name="description" content="Sotirov.Net - Server information" />
<meta name="keywords" content="Sotirov" />
<meta name="CVS" content="$Id: iss.en.phtml,v 1.1 2005/12/19 18:47:12 gsotirov Exp $" />
<meta name="robots" content="INDEX, FOLLOW" />
<link rel="icon" href="img/sotirov_net" />
<link rel="shortcut icon" href="img/sotirov_net" />
<link rel="stylesheet" href="style/default.css" media="screen, print" title="Default style" type="text/css" />
<link rel="stylesheet" href="style/speech.css" media="aural" type="text/css" />
<link rel="stylesheet" href="style/tty.css" media="tty" type="text/css" />

<link rel="top" href="index" title="Home" />
<link rel="up" href="iss" title="Up" />
</head>

<body>
<div id="header">
<h1>Information, Status, Statistics</h1>
</div>

<div id="navigation">
<p class="navigation">
[&nbsp;<a
href="/">Home</a>&nbsp;|&nbsp;<a
href="iss.bg.phtml" hreflang="bg" lang="bg">Български</a>&nbsp;]
</p>
</div>

<div>
<p>This information is provided mainly for the purposes of system
monitoring and is targeted to system administrators. However it can be
usefull and interesting for the regular users or visitors.</p>
</div>

<div id="info_status_stats">
<div id="server_himself">
<img alt="Server picture" id="server_pic" height="350" src="img/server"
title="The server himself" width="320" />
</div>
<div id="server_info_status_stats">
<h2>General info</h2>
<pre><?php
  printf("<i><abbr title=\"Operating System\">OS</abbr></i>           %s\n", os_info());
  printf("<i>Kernel</i>       %s\n", kernel_info());
  printf("<i>Distribution</i> %s\n", slack_ver());
  printf("<i>Machine</i>      %s\n", mach_info());
  printf("<i><abbr title=\"Central Processing Unit\">CPU</abbr></i>          %s\n", cpu_info());
?>
</pre>
<h2>Server status</h2>
<pre><?php
  $sysup = sysup();
  printf("<i>Up since</i>     %s\n", $sysup[0]);
  printf("<i>Up time</i>      %s\n", $sysup[1]);
  printf("<i>Load average</i> %s\n", loadavg());
  $meminfo = meminfo();
  printf("<i>Memory</i>       %s\n", $meminfo[0]);
  printf("<i>Swap</i>         %s\n", $meminfo[1]);
?>
</pre>
<h2>Bandwith utilization</h2>
<!-- The bandwidth bar program is available at:
 http://www.kernel.org/pub/software/web/bwbar/ -->
<?php
  $bwbar = fopen("bwbar/bwbar.txt", "r");
  fscanf($bwbar, "%f %f %s", $cur_bw, $max_bw, $unit);
  fclose($bwbar);
?>
<p>Currently <?php
  printf("%6.2f %s", $cur_bw, hr_bandw($unit));
?> of <?php printf("%6.2f %s", $max_bw, hr_bandw($unit));
?> used<br />
<img alt="Използван капацитет" height="6" src="bwbar/bwbar.png" width="602" />
</p>
<h2>Statistics</h2>
<ul>
<li><a href="stats/traffic/">Traffic</a>&nbsp;<img alt="[auth]"
height="16" src="/img/lock" title="Login required" width="16" /></li>
<li><a href="stats/hotsanic/">Load, Network, Partitions</a>&nbsp;
<img alt="[auth]" height="16" src="/img/lock" title="Login required"
width="16" /></li>
<li><a href="stats/awstats/awstats.pl?config=web">Web</a>&nbsp;<img
alt="[парола]" height="16" src="/img/lock" title="Изисква се удостоверяване"
width="16" />, <a href="stats/awstats/awstats.pl?config=ftp">FTP</a>&nbsp;<img
alt="[парола]" height="16" src="/img/lock" title="Изисква се удостоверяване"
width="16" /></li>
</ul>
</div>
</div>

<div id="conformance">
<hr />
<p class="align-center">
<!-- Valid XHTML 1.0 -->
&nbsp;<a href="http://validator.w3.org/check?uri=referer" hreflang="en">
<img alt="[Valid XHTML 1.0 icon]" height="31" src="img/valid-xhtml" title="Valid XHTML 1.0!" width="88" />
</a>&nbsp;
<!-- Valid CSS -->
<a href="http://jigsaw.w3.org/css-validator/validator?uri=gsotirov79.ddns.homelan.bg&amp;usermedium=all" hreflang="en">
<img alt="[Valid CSS icon]" height="31" src="img/valid-css" title="Valid CSS!" width="88" />
</a>&nbsp;
<!-- WAI WCAG Conformance -->
<a href="http://www.w3.org/WAI/WCAG1AA-Conformance/">
<img alt="[Level Triple-A conformance icon, W3C-WAI Web Content Accessibility Guidelines 1.0]"
height="31" src="img/wai-wcag-1.0-2a" title="Explanation of Level Triple-A Conformance" width="88" />
</a>&nbsp;
<!-- WebXact -->
<a href="http://webxact.watchfire.com/submit.aspx?SCANURL=http://gsotirov79.ddns.homelan.bg/iss&amp;GL=wcag1-aa" hreflang="en">
<img alt="[Verification of Level AA through WebXact]" height="31" src="/img/webxact" title="Verification of Level AA through WebXact" width="88" />
</a>&nbsp;
<!-- UTF-8 Encoded -->
<a href="http://www.unicode.org/" hreflang="en">
<img alt="[Encoded in UTF-8 icon]" height="31" src="img/unicode" title="Encoded in UTF-8!" width="88" />
</a>&nbsp;
</p>
</div>

<div id="powered_by">
<p>&nbsp;<a href="http://www.kernel.org/" hreflang="en">
<img alt="[Powered by Linux]" height="31" src="img/linux_pb" title="Powered by Linux" width="88" />
</a>&nbsp;<a href="http://www.apache.org/" hreflang="en">
<img alt="[Powered by Apache]" height="31" src="img/apache_pb" title="Powered by Apache" width="88" />
</a>&nbsp;<a href="http://www.php.net/" hreflang="en">
<img alt="[Powered by PHP]" height="31" src="img/php_pb" title="Powered by PHP" width="88" />
</a>&nbsp;</p>
</div>

<div id="generated">
<p>Page generated: <?php echo date("Y-m-d H:i:s T"); ?></p>
</div>

</body>
</html>
