<?php
  $I18N_LANG = 'en';
  print("<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n");

  include '../../news.php.inc';
  include 'nutil.php.inc';
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="bg" lang="bg">

<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Sotirov-BG.Net - Новини</title>
<meta name="author" content="Георги Д. Сотиров, gdsotirov@dir.bg" />
<meta name="description" content="Новинарска страница на Sotirov-BG.Net" />
<meta name="keywords" content="sotirov.net, Georgi Sotirov" />
<meta name="CVS" content="$Id: index.bg.phtml,v 1.19 2006/06/13 18:32:53 gsotirov Exp $" />
<link rel="icon" href="/img/sotirov_net" />
<link rel="shortcut icon" href="/img/sotirov_net" />
<link rel="stylesheet" href="/style/default.css" media="screen, print" title="Подразбрано" type="text/css" />
<link rel="stylesheet" href="news.css" media="screen, print" title="Подразбрано" type="text/css" />
<link rel="stylesheet" href="/style/speech.css" media="aural" type="text/css" />
<link rel="stylesheet" href="/style/tty.css" media="tty" type="text/css" />
<link rel="alternate" type="text/html" href="index.en.phtml" hreflang="en" lang="en" title="Sotirov-BG.Net News" />
<link rel="alternate" href="feed?f=atom" title="Новини от Sotirov.net (Atom)" type="application/atom+xml" />
<link rel="alternate" href="feed?f=rss&amp;v=2.0" title="Новини от Sotirov.net (RSS 2.0)" type="application/rss+xml" />
<link rel="alternate" href="feed?f=rss&amp;v=1.0" title="Новини от Sotirov.net (RSS 1.0)" type="application/rdf+xml" />
<link rel="alternate" href="feed?f=rss&amp;v=0.91" title="Новини от Sotirov.net (RSS 0.91)" type="application/rss+xml" />
<link rel="alternate" href="feed?f=rss&amp;v=0.9" title="Новини от Sotirov.net (RSS 0.9)" type="application/rdf+xml" />
<link rel="up" href="news" title="Up" />
</head>
<?php
  function get_month($number) {
    switch ($number) {
      case  1: return 'Януари';
      case  2: return 'Февруари';
      case  3: return 'Март';
      case  4: return 'Април';
      case  5: return 'Май';
      case  6: return 'Юни';
      case  7: return 'Юли';
      case  8: return 'Август';
      case  9: return 'Септември';
      case 10: return 'Октомври';
      case 11: return 'Ноември';
      case 12: return 'Декември';
    }
  }

  if ( !$news_c = mysql_connect($news_host, $news_user, $news_pass) )
    $error = CANNOT_CONNECT;
  if ( !mysql_select_db($news_db, $news_c) )
    $error = CANNOT_SEL_DB;
?>
<body>
<div id="header">
<h1>Новини от Sotirov-BG.Net</h1>
</div>

<div id="navigation">
<map id="nav_gen">
<ul>
<li><a href="/">Начало</a></li>
<li><a href="/news/">Последни новини</a></li>
<li><a href="#copyright">Авторски права</a></li>
</ul></map>
<div id="sidebar">
<map id="nav_lang">
<h2>Език</h2>
<ul>
<li><a href="index.en.phtml" hreflang="en" lang="en">English</a></li>
</ul></map>
<map id="nav_alt">
<h2>Обединяване</h2>
<ul>
<li><img alt="Емисия:" src="/icons/feed"/>&nbsp;<a href="feed?f=atom" type="application/atom+xml">Atom Емисия</a></li>
<li><img alt="Емисия:" src="/icons/feed"/>&nbsp;<a href="feed?f=rss&amp;v=2.0" type="application/rss+xml">RSS 2.0 Емисия</a></li>
</ul>
<ul>
<li><a href="feed?f=rss&amp;v=1.0" type="application/rdf+xml">RSS 1.0 Емисия</a></li>
<li><a href="feed?f=rss&amp;v=0.91" type="application/rss+xml">RSS 0.91 Емисия</a></li>
<li><a href="feed?f=rss&amp;v=0.9" type="application/rdf+xml">RSS 0.9 Емисия</a></li>
</ul></map>
<map id="nav_arch">
<h2>Архив</h2>
<ul>
<?php
  if ( !isset($error) ) {
    $query  = "SELECT Month(nws.posted) AS Month, Year(nws.posted) AS Year ";
    $query .= "FROM news_bg AS nws ";
    $query .= "GROUP BY Month(nws.posted), Year(nws.posted) ";
    $query .= "ORDER BY Year(nws.posted) DESC, Month(nws.posted) DESC";

    $res = mysql_query($query, $news_c);
    if ( mysql_num_rows($res) > 0 ) {
      while ( $item = mysql_fetch_array($res, MYSQL_ASSOC) ) {
        $link = "?m=".$item['Month']."&amp;y=".$item['Year'];
        $name = get_month($item['Month']).", ".$item['Year'];
        print("<li><a href=\"$link\">$name</a></li>\n");
      }
    }
    mysql_free_result($res);
  }
?>
</ul>
</map>
<div id="search">
<h2>Търсене</h2>
<p>Търсене в заглавия и текст на новините</p>
<form action="?"  id="newsSearch" method="get">
<p><input id="q" name="q" maxlength="255" type="text" size="15" />&nbsp;<br />
<input type="submit" value="Търсене" /></p>
</form>
</div>
</div>
</div>

<div id="content">
<?php
  if ( isset($_REQUEST['id']) )
    $news_id = $_REQUEST['id'];
  if ( isset($_REQUEST['q']) )
    $q = $_REQUEST['q'];
  if ( isset($_REQUEST['m']) )
    $month = $_REQUEST['m'];
  if ( isset($_REQUEST['y']) )
    $year = $_REQUEST['y'];

  if ( !isset($error) ) {
    $query  = "SELECT nws.id, nws.title, nws.body, nws.author, nws.posted, ";
    $query .= "nws.updated, usr.name_bg, usr.firstname_bg, usr.email ";
    $query .= "FROM news_bg AS nws, users AS usr ";
    // Search by ID
    if ( isset($news_id) ) {
      $query .= "WHERE nws.id = $news_id AND nws.posted <> '0000-00-00 00:00:00' ";
      $query .= "AND nws.author = usr.id ";
    }
    // Search by month, year (archive)
    elseif ( isset($month) || isset($year) ) {
      $query .= "WHERE nws.posted <> '0000-00-00 00:00:00' AND nws.author = usr.id ";
      if ( isset($month) ) {
        $query .= "AND Month(nws.posted) = $month ";
        if ( isset($year) )
          $query .= "AND Year(nws.posted) = $year ";
        else
          $query .= "AND Year(nws.posted) = ".date('Y');
      }
      else
        $query .= "WHERE Year(nws.posted) = $year ";
      $query .= "ORDER BY nws.posted DESC";
    }
    // Search by string in the text
    elseif ( isset($q) ) {
      $query .= "WHERE nws.posted <> '0000-00-00 00:00:00' AND nws.author = usr.id ";
      $query .= "AND (nws.title LIKE '%$q%' OR nws.body LIKE '%$q%')";
      $query .= "ORDER BY nws.posted DESC";
    }
    // Default - show last ten news
    else {
      $query .= "WHERE nws.posted <> '0000-00-00 00:00:00' AND nws.author = usr.id ";
      $query .= "ORDER BY nws.posted DESC";
    }
    $res = mysql_query($query, $news_c);
    if ( mysql_num_rows($res) > 0 ) {
      while ( $item = mysql_fetch_array($res, MYSQL_ASSOC) ) {
        print("<div id=\"newsid_".$item['id']."\">\n");
        mark_text($q, $item['title']);
        print("<h3>".$item['title']."</h3>\n");
        $user_name = $item['firstname_bg']." ".$item['name_bg'];
        print("<p class=\"italic\">Публикувано от <a href=\"mailto:$user_name &lt;".$item['email']."&gt;\">$user_name</a>");
        print(" на ".$item['posted']."&nbsp;<abbr lang=\"en\" title=\"Eastern European Time\">EET</abbr>");
        if ( strtotime($item['updated']) > strtotime($item['posted']) ) {
          print(", променено на ".$item['updated']."&nbsp;<abbr lang=\"en\" title=\"Eastern European Time\">EET</abbr>");
        }
        print("</p>\n");
        print("<div class=\"body\">\n");
        mark_text($q, $item['body']);
        print($item['body']);
        print("</div>\n");
        print("</div>\n\n");
      }
    }
    else {
      if ( isset($news_id) )
        print("<p>Няма такава новина.</p>\n");
      elseif ( isset($month) or isset($year) ) {
        print("<p>Няма новини от ".get_month($month));
        if ( isset($year) )
          print(" $year.</p>\n");
        else
          print(date('Y')."</p>\n");
      }
      elseif ( isset($q) )
        print("<p>Търсеният от вас низ '$q' не съвпадна с никакви новини.</p>");
      else
        print("<p>Новините не са достъпни в момента.</p>\n");
    }
    mysql_free_result($res);
  }
  else
    print("<p>Новините не са достъпни в момента.</p>\n");
?>
</div>

<div id="copyright" class="clear">
<hr />
<p>Автор &copy; 2004-2006 <a href="mailto:gdsotirov@dir.bg">Георги Д. Сотиров</a><br />
Всички права запазени</p>
</div>

<div id="conformance">
<map id="conformancebar">
<p>
<!-- Valid XHTML 1.0 -->
<a href="http://validator.w3.org/check?uri=referer" hreflang="en">
<img alt="[Валиден XHTML 1.0]" height="31" src="/img/valid-xhtml" title="Валиден XHTML 1.0!" width="88" /></a>&nbsp;
<!-- Valid CSS -->
<a href="http://jigsaw.w3.org/css-validator/validator?uri=gsotirov79.ddns.homelan.bg&amp;usermedium=all" hreflang="en">
<img alt="[Валиден CSS]" height="31" src="/img/valid-css" title="Валиден CSS!" width="88" /></a>&nbsp;
<!-- WAI WCAG Conformance -->
<a href="http://www.w3.org/WAI/WCAG1AA-Conformance" hreflang="en">
<img alt="[Икона за съответствие с ниво двойно А, W3C-WAI Web Content Accessibility Guidelines 1.0]"
height="31" src="/img/wai-wcag-1.0-2a" title="Обяснение на съотвестстие със ниво двойно А" width="88" /></a>&nbsp;
<!-- Valid Atom 1.0 -->
<a href="http://feedvalidator.org/check.cgi?url=http://gsotirov79.ddns.homelan.bg/news/feed&amp;f=atom"><img src="/img/valid-atom" alt="[Валиден Atom 1.0]" title="Проверете моята Atom 1.0 емисия" /></a>&nbsp;
<!-- WebXact -->
<a href="http://webxact.watchfire.com/submit.aspx?SCANURL=http://gsotirov79.ddns.homelan.bg/index&amp;GL=wcag1-aa" hreflang="en">
<img alt="[Проверка на ниво AA през WebXact]" height="31" src="/img/webxact" title="Проверка на ниво AA през WebXact" width="88" /></a>&nbsp;
<!-- UTF-8 Encoded -->
<a href="http://www.unicode.org/" hreflang="en">
<img alt="[Кодирано в UTF-8]" height="31" src="/img/unicode" title="Кодирано в UTF-8!" width="88" /></a>
</p></map>
</div>

<div id="poweredby">
<map id="poweredbybar">
<p><a href="http://www.kernel.org/" hreflang="en">
<img alt="[Работи с моща на Linux]" height="31" src="/img/linux_pb" title="Работи с моща на Linux" width="88" /></a>&nbsp;
<a href="http://www.apache.org/" hreflang="en">
<img alt="[Работи с моща на Apache]" height="31" src="/img/apache_pb" title="Работи с моща на Apache" width="88" /></a>&nbsp;
<a href="http://www.php.net/" hreflang="en">
<img alt="[Работи с моща на PHP]" height="31" src="/img/php_pb" title="Работи с моща на PHP" width="88" /></a>&nbsp;
<a href="http://www.mysql.com/" hreflang="en">
<img alt="[Работи с MySQL]" height="31" src="/img/mysql_pb" title="Работи с MySQL" width="88" /></a>
</p></map>
</div>

</body>
<?php
  mysql_close($news_c);
?>
</html>

