<?php
  $I18N_LANG = 'en';
  print("<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n");

  include '../../news.php.inc';
  include 'nutil.php.inc';

  function get_month($number) {
    switch ($number) {
      case  1: $month = 'Януари';     break;
      case  2: $month = 'Февруари';   break;
      case  3: $month = 'Март';       break;
      case  4: $month = 'Април';      break;
      case  5: $month = 'Май';        break;
      case  6: $month = 'Юни';        break;
      case  7: $month = 'Юли';        break;
      case  8: $month = 'Август';     break;
      case  9: $month = 'Септември';  break;
      case 10: $month = 'Октомври';   break;
      case 11: $month = 'Ноември';    break;
      case 12: $month = 'Декември';   break;
      default: $month = '';
    }

    return $month;
  }

  if ( !$news_c = mysql_connect($news_host, $news_user, $news_pass) ) {
    $error = CANNOT_CONNECT;
  }
  if ( !mysql_select_db($news_db, $news_c) ) {
    $error = CANNOT_SEL_DB;
  }

  if ( isset($_REQUEST['id']) ) {
    $news_id = $_REQUEST['id'];
    if ( isset($news_id) && is_numeric($news_id) ) {
      $qtitle = "SELECT title from news_bg WHERE id = ".(int)$news_id.";";
      $ntres = mysql_query($qtitle, $news_c);
      $ntitle = mysql_result($ntres, 0);
      mysql_free_result($ntres);
    }
  }
  if ( isset($_REQUEST['q']) ) {
    $q = $_REQUEST['q'];
    $safe_tokens = tokenize($q, 5);
  }
  if ( isset($_REQUEST['m']) && is_numeric($_REQUEST['m']) ) {
    $month = (int)$_REQUEST['m'];
    if ( $month < 1 || $month > 12 ) {
      unset($month);
    }
  }
  if ( isset($_REQUEST['y']) && is_numeric($_REQUEST['y']) ) {
    $year = $_REQUEST['y'];
    if ( $year < 2004 && $year > date("Y") ) {
      unset($year);
    }
  }
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="bg" lang="bg">

<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<?php
  if ( isset($news_id) && is_numeric($news_id) ) {
    $page_title = "Sotirov-BG.Net - ".$ntitle;
  }
  elseif ( isset($month) || isset($year) ) {
    if ( isset($month) ) {
      $page_title = sprintf("Sotirov-BG.Net - Новини от %s, %4d", get_month($month), $year);
    }
    else {
      $page_title = sprintf("Sotirov-BG.Net - Новини за %4d г.", $year);
    }
  }
  elseif ( isset($q) ) {
    $page_title = sprintf("Sotirov-BG.Net - Новини съдържащи &quot;%s&quot;", htmlspecialchars($q, ENT_QUOTES | ENT_XHTML, 'UTF-8'));
  }
  else {
    $page_title = "Sotirov-BG.Net - Новини";
  }
?>
<title><?php echo $page_title ?></title>
<meta name="author" content="Георги Д. Сотиров, gdsotirov@dir.bg" />
<meta name="description" content="Sotirov-BG.Net - Новини" />
<meta name="keywords" content="Георги Сотиров, Сотиров, сървър, проекти, страници, новини" />
<meta name="robots" content="INDEX, FOLLOW" />
<meta name="robots" content="ARCHIVE" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link rel="icon" href="/img/sotirov_net" />
<link rel="shortcut icon" href="/img/sotirov_net" />
<link rel="stylesheet" media="screen, print" title="По подразбриране" type="text/css" href="/style/default.css" />
<link rel="stylesheet" media="screen, print" title="По подразбриране" type="text/css" href="/style/news.css" />
<link rel="stylesheet" media="speech" title="По подразбиране" type="text/css" href="/style/speech.css" />
<link rel="stylesheet" media="tty" title="По подразбиране" type="text/css" href="/style/tty.css" />
<link rel="alternate" type="text/html" href="index.en?<?php echo $_SERVER['QUERY_STRING'] ?>" hreflang="en" lang="en" title="<?php echo $page_title ?>" />
<link rel="alternate" href="feed?f=atom" title="Новини от Sotirov-BG.Net (Atom)" type="application/atom+xml" />
<link rel="alternate" href="feed?f=rss&amp;v=2.0" title="Новини от Sotirov-BG.Net (RSS 2.0)" type="application/rss+xml" />
<link rel="alternate" href="feed?f=rss&amp;v=1.0" title="Новини от Sotirov-BG.Net (RSS 1.0)" type="application/rdf+xml" />
<link rel="alternate" href="feed?f=rss&amp;v=0.91" title="Новини от Sotirov-BG.Net (RSS 0.91)" type="application/rss+xml" />
<link rel="alternate" href="feed?f=rss&amp;v=0.9" title="Новини от Sotirov-BG.Net (RSS 0.9)" type="application/rdf+xml" />
<link rel="start" href="../" title="Начало" />
</head>
<body>
<div id="header">
<?php
  if ( isset($news_id) && is_numeric($news_id) ) {
    printf("<h1>Sotirov-BG.Net - %s</h1>", $ntitle);
  }
  elseif ( isset($month) || isset($year) ) {
    if ( isset($month) ) {
      printf("<h1>Новини от %s, %4d</h1>", get_month($month), $year);
    }
    else {
      printf("<h1>Новини за %4d г.</h1>", $year);
    }
  }
  elseif ( isset($q) ) {
    printf("<h1>Новини съдържащи &quot;%s&quot;</h1>", htmlspecialchars($q, ENT_QUOTES | ENT_XHTML, 'UTF-8'));
  }
  else {
    printf("<h1>Новини от Sotirov-BG.Net</h1>");
  }
?>
</div>

<div id="navigation">
<div id="nav_gen">
<map id="nav_gen_map"><ul>
<li><a href="/">Начало</a></li>
<li><a href="/news/">Последни новини</a></li>
<li><a href="#copyright">Авторски права</a></li>
</ul></map></div>

<div id="sidebar">
<div id="nav_lang">
<h2>Език</h2>
<map id="nav_lang_map"><ul>
<li><a href="index.en?<?php echo $_SERVER['QUERY_STRING'] ?>" hreflang="en" lang="en">English</a></li>
</ul></map></div>

<div id="nav_alt">
<h2>Обединяване</h2>
<map id="nav_alt_map"><ul>
<li><img alt="Емисия:" longdesc="http://feedicons.com/" src="/icons/feed"/>&nbsp;<a href="feed?f=atom" type="application/atom+xml">Atom Емисия</a></li>
<li><img alt="Емисия:" longdesc="http://feedicons.com/" src="/icons/feed"/>&nbsp;<a href="feed?f=rss&amp;v=2.0" type="application/rss+xml">RSS 2.0 Емисия</a></li>
<li><img alt="Емисия:" longdesc="http://feedicons.com/" src="/icons/feed"/>&nbsp;<a href="feed?f=rss&amp;v=1.0" type="application/rdf+xml">RSS 1.0 Емисия</a></li>
</ul>
<ul>
<li><a href="feed?f=rss&amp;v=0.91" type="application/rss+xml">RSS 0.91 Емисия</a></li>
<li><a href="feed?f=rss&amp;v=0.9" type="application/rdf+xml">RSS 0.9 Емисия</a></li>
</ul></map></div>

<div id="nav_arch">
<h2>Архив</h2>
<map id="nav_arch_map"><ul>
<?php
  if ( !isset($error) ) {
    $query  = "SELECT Month(nws.posted) AS Month, Year(nws.posted) AS Year ";
    $query .= "FROM news_bg AS nws ";
    $query .= "GROUP BY Month(nws.posted), Year(nws.posted) ";
    $query .= "ORDER BY Year(nws.posted) DESC, Month(nws.posted) DESC";

    $res = mysql_query($query, $news_c);
    if ( mysql_num_rows($res) > 0 ) {
      while ( $item = mysql_fetch_array($res, MYSQL_ASSOC) ) {
        $link = "?m=".$item['Month']."&amp;y=".$item['Year'];
        $name = get_month($item['Month']).", ".$item['Year'];
        print("<li><a href=\"$link\">$name</a></li>\n");
      }
    }
    mysql_free_result($res);
  }
?>
</ul></map></div>

<div id="search">
<h2>Търсене</h2>
<p>Търсене в заглавия и текст на новините</p>
<form action="?" id="newsSearch" method="get">
<p><label for="q">Запитване:&nbsp;<input alt="Текст за търсене" id="q" name="q" maxlength="255" size="15" type="text" /></label><br />
<input name="search" type="submit" value="Търсене" /></p>
</form>
</div></div></div>

<div id="content">
<?php
  if ( isset($error) ) {
    print("<p class=\"error\">Новините не са достъпни в момента.</p>\n");
  }
  else {
    $query  = "SELECT nws.id, nws.title, nws.body, nws.author, nws.posted, ";
    $query .= "nws.updated, usr.name_bg, usr.firstname_bg, usr.email ";
    $query .= "FROM news_bg AS nws, users AS usr ";
    // Search by ID
    if ( isset($news_id) ) {
      if ( is_numeric($news_id) ) {
        $query .= "WHERE nws.id = ".(int)$news_id." AND nws.posted <> '0000-00-00 00:00:00' ";
        $query .= "AND nws.author = usr.id ";
      }
      else {
        print("<p class=\"error\">Недействителен идентификатор на новина '".htmlentities($news_id, ENT_QUOTES, "UTF-8")."'!</p>\n");
        $query .= "WHERE nws.posted <> '0000-00-00 00:00:00' AND nws.author = usr.id ";
        $query .= "ORDER BY nws.posted DESC ";
        $query .= "LIMIT 10";
      }
    }
    // Search by month, year (archive)
    elseif ( isset($month) || isset($year) ) {
      $query .= "WHERE nws.posted <> '0000-00-00 00:00:00' AND nws.author = usr.id ";
      if ( isset($month) ) {
        if ( is_numeric($month) && (int)$month >= 1 && (int)$month <= 12 ) {
          $query .= "AND Month(nws.posted) = $month ";
        }
        else {
          print("<p class=\"error\">Недействителен номер на месец '".htmlentities($month, ENT_QUOTES, "UTF-8")."'!</p>\n");
          unset($month);
        }
      }
      if ( isset($year) && is_numeric($year) && (int)$year >= 2004 && (int)$year <= date('Y') ) {
        $query .= "AND Year(nws.posted) = $year ";
      }
      else {
        print("<p class=\"error\">Недействителна година '".htmlentities($year, ENT_QUOTES, "UTF-8")."'!</p>\n");
        $year = date('Y');
        $query .= "AND Year(nws.posted) = $year ";
      }
      $query .= "ORDER BY nws.posted DESC";
    }
    // Search by tokens in the text
    elseif ( isset($q) ) {
      $query .= "WHERE nws.posted <> '0000-00-00 00:00:00' AND nws.author = usr.id AND (";
      foreach ( $safe_tokens as $idx => $token ) {
        $sql_token = mysql_real_escape_string($token, $news_c);
        if ( $idx > 0 ) {
          $query .= "AND (nws.title LIKE '%$sql_token%' OR nws.body LIKE '%$sql_token%') ";
        }
        else {
          $query .= "(nws.title LIKE '%$sql_token%' OR nws.body LIKE '%$sql_token%') ";
        }
      }
      $query .= ") ";
      $query .= "ORDER BY nws.posted DESC";
    }
    // Default - show last ten news
    else {
      $query .= "WHERE nws.posted <> '0000-00-00 00:00:00' AND nws.author = usr.id ";
      $query .= "ORDER BY nws.posted DESC ";
      $query .= "LIMIT 10";
    }

    $res = mysql_query($query, $news_c);
    if ( mysql_num_rows($res) > 0 ) {
      while ( $item = mysql_fetch_array($res, MYSQL_ASSOC) ) {
        print("<div class=\"news\" id=\"newsid_".$item['id']."\">\n");
        if ( isset($q) ) {
          mark_token_text($safe_tokens, $item['title']);
        }
        print("<h3>".$item['title']."</h3>\n");
        $mail_to = $item['firstname_bg']."%20".$item['name_bg']."%20%3C".$item['email']."%3E";
        $user_name = $item['firstname_bg']." ".$item['name_bg'];
        print("<p class=\"italic\">Публикувано от ");
        print("<a href=\"mailto:".$mail_to."\">");
        print($user_name."</a>");
        print(" на ".$item['posted']."&nbsp;<abbr lang=\"en\" title=\"Eastern European Time\">EET</abbr>");
        if ( strtotime($item['updated']) > strtotime($item['posted']) ) {
          print(", променено на ".$item['updated']."&nbsp;<abbr lang=\"en\" title=\"Eastern European Time\">EET</abbr>");
        }
        print("</p>\n");
        print("<div class=\"body\">\n");
        if ( isset($q) ) {
          mark_token_html($safe_tokens, $item['body']);
        }
        print($item['body']);
        print("</div>\n");
        print("</div>\n\n");
      }
    }
    else {
      if ( isset($news_id) ) {
        print("<p class=\"error\">Няма такава новина.</p>\n");
      }
      elseif ( isset($month) || isset($year) ) {
        print("<p class=\"error\">Няма новини от ");
        if ( isset($month) ) {
          print(get_month($month).", ");
        }
        print("$year</p>\n");
      }
      elseif ( isset($q) ) {
        print("<p class=\"info\">Търсеният от вас низ '".htmlentities($q, ENT_QUOTES, "UTF-8")."' не съвпадна с никакви новини.</p>");
      }
      else {
        print("<p class=\"error\">Новините не са достъпни в момента.</p>\n");
      }
    }
    mysql_free_result($res);
  }
?>
</div>

<div id="copyright" class="clear">
<hr />
<p>Автор &copy; 2004-2020 <a href="mailto:gdsotirov@dir.bg">Георги Д. Сотиров</a><br />
Всички права запазени</p>
</div>

<div id="conformance">
<map id="conformancebar">
<p>
<!-- Valid XHTML 1.0 -->
<a href="https://validator.w3.org/check?uri=referer" hreflang="en">
<img alt="[Икона Валиден XHTML 1.0]" height="31" longdesc="https://validator.w3.org/" src="/img/valid-xhtml" title="Валиден XHTML 1.0!" width="88" /></a>
<!-- Valid CSS -->
<a href="https://jigsaw.w3.org/css-validator/check/referer" hreflang="en">
<img alt="[Икона Валиден CSS]" height="31" longdesc="https://jigsaw.w3.org/" src="/img/valid-css" title="Валиден CSS!" width="88" /></a>
<!-- Valid Atom 1.0 -->
<a href="https://validator.w3.org/feed/check.cgi?url=https://<?php echo $_SERVER['SERVER_NAME'] ?>/news/feed&amp;f=atom">
<img alt="[Валиден Atom 1.0]" height="31" longdesc="https://validator.w3.org/feed/" src="/img/valid-atom" title="Проверете моята Atom емисия" width="88" /></a>
<!-- Valid RSS 2.0 -->
<a href="https://validator.w3.org/feed/check.cgi?url=https://<?php echo $_SERVER['SERVER_NAME'] ?>/news/feed?f=rss&amp;v=2.0">
<img alt="[Валиден RSS]" height="31" longdesc="https://validator.w3.org/feed/" src="/img/valid-rss" title="Проверете моята RSS емисия" width="88" /></a>
<!-- WAI WCAG Conformance -->
<a href="https://www.w3.org/WAI/WCAG1AA-Conformance" hreflang="en">
<img alt="[Икона за съответствие с ниво двойно А]" height="31" longdesc="https://www.w3.org/WAI/" src="/img/wai-wcag-1.0-2a" title="Обяснение на съотвестстие със ниво двойно А" width="88" /></a>
<!-- UTF-8 Encoded -->
<a href="https://www.unicode.org/" hreflang="en">
<img alt="[Икона Кодирано в UTF-8]" height="31" longdesc="https://www.unicode.org/" src="/img/unicode" title="Кодирано в UTF-8!" width="88" /></a>
</p></map>
</div>

<div id="poweredby">
<map id="poweredbybar">
<p><a href="https://www.kernel.org/" hreflang="en">
<img alt="[Работи с мощта на Linux]" height="31" longdesc="https://www.kernel.org/" src="/img/linux_pb" title="Работи с мощта на Linux" width="88" /></a>
<a href="https://www.apache.org/" hreflang="en">
<img alt="[Работи с мощта на Apache]" height="31" longdesc="https://www.apache.org/" src="/img/apache_pb" title="Работи с мощта на Apache" width="88" /></a>
<a href="https://www.mysql.com/" hreflang="en">
<img alt="[Работи с MySQL]" height="31" longdesc="https://www.mysql.com/" src="/img/mysql_pb" title="Работи с MySQL" width="88" /></a>
<a href="https://www.php.net/" hreflang="en">
<img alt="[Работи с мощта на PHP]" height="31" longdesc="https://www.php.net/" src="/img/php_pb" title="Работи с мощта на PHP" width="88" /></a>
</p></map>
</div>

</body>
<?php
  mysql_close($news_c);
?>
</html>

