<?php
  $I18N_LANG = 'en';
  print("<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n");

  include '../../news.php.inc';
  include 'nutil.php.inc';
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Sotirov-BG.Net - News</title>
<meta name="author" content="Georgi D. Sotirov, gdsotirov@dir.bg" />
<meta name="description" content="Sotirov-BG.Net - News" />
<meta name="keywords" content="Georgi Sotirov, Sotirov, server, projects, pages, news" />
<meta name="robots" content="INDEX, FOLLOW" />
<meta name="robots" content="ARCHIVE" />
<meta name="CVS" content="$Id: index.en.phtml,v 1.28 2006/08/01 21:28:18 gsotirov Exp $" />
<link rel="icon" href="/img/sotirov_net" />
<link rel="shortcut icon" href="/img/sotirov_net" />
<link rel="stylesheet" media="screen, print" title="Default" type="text/css" href="/style/default.css" />
<link rel="stylesheet" media="screen, print" title="Default" type="text/css" href="news.css" />
<link rel="stylesheet" media="aural" title="Default" type="text/css" href="/style/speech.css" />
<link rel="stylesheet" media="tty" title="Default" type="text/css" href="/style/tty.css" />
<link rel="alternate" type="text/html" href="index.bg.phtml" hreflang="bg" lang="bg" title="Новини от Sotirov-BG.Net" />
<link rel="alternate" href="feed?f=atom" title="Sotirov-BG.Net News (Atom)" type="application/atom+xml" />
<link rel="alternate" href="feed?f=rss&amp;v=2.0" title="Sotirov-BG.Net News (RSS 2.0)" type="application/rss+xml" />
<link rel="alternate" href="feed?f=rss&amp;v=1.0" title="Sotirov-BG.Net News (RSS 1.0)" type="application/rdf+xml" />
<link rel="alternate" href="feed?f=rss&amp;v=0.91" title="Sotirov-BG.Net News (RSS 0.91)" type="application/rss+xml" />
<link rel="alternate" href="feed?f=rss&amp;v=0.9" title="Sotirov-BG.Net News (RSS 0.9)" type="application/rdf+xml" />
<link rel="start" href="../" title="Home" />
</head>
<?php
  function get_month($number) {
    switch ($number) {
      case  1: return 'January';
      case  2: return 'February';
      case  3: return 'March';
      case  4: return 'April';
      case  5: return 'May';
      case  6: return 'June';
      case  7: return 'July';
      case  8: return 'August';
      case  9: return 'September';
      case 10: return 'October';
      case 11: return 'November';
      case 12: return 'December';
    }
  }

  if ( !$news_c = mysql_connect($news_host, $news_user, $news_pass) )
    $error = CANNOT_CONNECT;
  if ( !mysql_select_db($news_db, $news_c) )
    $error = CANNOT_SEL_DB;
?>
<body>
<div id="header">
<h1>Sotirov-BG.Net News</h1>
</div>

<div id="navigation">
<div id="nav_gen">
<map id="nav_gen_map"><ul>
<li><a href="/">Home</a></li>
<li><a href="/news/">Last news</a></li>
<li><a href="#copyright">Copyright</a></li>
</ul></map></div>

<div id="sidebar">
<div id="nav_lang">
<h2>Language</h2>
<map id="nav_lang_map"><ul>
<li><a href="index.bg.phtml" hreflang="bg" lang="bg">Български</a></li>
</ul></map></div>

<div id="nav_alt">
<h2>Syndication</h2>
<map id="nav_alt_map"><ul>
<li><img alt="Feed:" longdesc="http://feedicons.com/" src="/icons/feed"/>&nbsp;<a href="feed?f=atom" type="application/atom+xml">Atom Feed</a></li>
<li><img alt="Feed:" longdesc="http://feedicons.com/" src="/icons/feed"/>&nbsp;<a href="feed?f=rss&amp;v=2.0" type="application/rss+xml">RSS 2.0 Feed</a></li>
<li><img alt="Feed:" longdesc="http://feedicons.com/" src="/icons/feed"/>&nbsp;<a href="feed?f=rss&amp;v=1.0" type="application/rdf+xml">RSS 1.0 Feed</a></li>
</ul>
<ul>
<li><a href="feed?f=rss&amp;v=0.91" type="application/rss+xml">RSS 0.91 Feed</a></li>
<li><a href="feed?f=rss&amp;v=0.9" type="application/rdf+xml">RSS 0.9 Feed</a></li>
</ul></map></div>

<div id="nav_arch">
<h2>Archive</h2>
<map id="nav_arch_map"><ul>
<?php
  if ( !isset($error) ) {
    $query  = "SELECT Month(nws.posted) AS Month, Year(nws.posted) AS Year ";
    $query .= "FROM news AS nws ";
    $query .= "GROUP BY Month(nws.posted), Year(nws.posted) ";
    $query .= "ORDER BY Year(nws.posted) DESC, Month(nws.posted) DESC";

    $res = mysql_query($query, $news_c);
    if ( mysql_num_rows($res) > 0 ) {
      while ( $item = mysql_fetch_array($res, MYSQL_ASSOC) ) {
        $link = "?m=".$item['Month']."&amp;y=".$item['Year'];
        $name = get_month($item['Month']).", ".$item['Year'];
        print("<li><a href=\"$link\">$name</a></li>\n");
      }
    }
    mysql_free_result($res);
  }
?>
</ul></map></div>

<div id="search">
<h2>Search</h2>
<p>Search in titles and text of the news</p>
<form action="?" id="newsSearch" method="get">
<p><label for="q">Query:&nbsp;<input alt="Text to search" id="q" name="q" maxlength="255" size="15" type="text" value="Text to search" /></label><br />
<input name="search" type="submit" value="Search" /></p>
</form>
</div></div></div>

<div id="content">
<?php
if ( isset($_REQUEST['id']) )
    $news_id = $_REQUEST['id'];
  if ( isset($_REQUEST['q']) )
    $q = $_REQUEST['q'];
  if ( isset($_REQUEST['m']) )
    $month = $_REQUEST['m'];
  if ( isset($_REQUEST['y']) )
    $year = $_REQUEST['y'];

  if ( !isset($error) ) {
    $query  = "SELECT nws.id, nws.title, nws.body, nws.author, nws.posted, ";
    $query .= "nws.updated, usr.name, usr.firstname, usr.email ";
    $query .= "FROM news AS nws, users AS usr ";
    // Search by ID
    if ( isset($news_id) ) {
      $query .= "WHERE nws.id = $news_id AND nws.posted <> '0000-00-00 00:00:00' ";
      $query .= "AND nws.author = usr.id ";
    }
    // Search by month, year (archive)
    elseif ( isset($month) || isset($year) ) {
      $query .= "WHERE nws.posted <> '0000-00-00 00:00:00' AND nws.author = usr.id ";
      if ( isset($month) ) {
        $query .= "AND Month(nws.posted) = $month ";
        if ( isset($year) )
          $query .= "AND Year(nws.posted) = $year ";
        else
          $query .= "AND Year(nws.posted) = ".date('Y');
      }
      else
        $query .= "WHERE Year(nws.posted) = $year ";
      $query .= "ORDER BY nws.posted DESC";
    }
    // Search by string in the text
    elseif ( isset($q) ) {
      $query .= "WHERE nws.posted <> '0000-00-00 00:00:00' AND nws.author = usr.id ";
      $safe_q = mysql_real_escape_string($q, $news_c);
      $query .= "AND (nws.title LIKE '%$safe_q%' OR nws.body LIKE '%$safe_q%')";
      $query .= "ORDER BY nws.posted DESC";
    }
    // Default - show last ten news
    else {
      $query .= "WHERE nws.posted <> '0000-00-00 00:00:00' AND nws.author = usr.id ";
      $query .= "ORDER BY nws.posted DESC";
    }
    $res = mysql_query($query, $news_c);
    if ( mysql_num_rows($res) > 0 ) {
      while ( $item = mysql_fetch_array($res, MYSQL_ASSOC) ) {
        print("<div id=\"newsid_".$item['id']."\">\n");
        print("<h3>".$item['title']."</h3>\n");
        $mail_to = $item['firstname']."%20".$item['name']."%20%3C".$item['email']."%3E";
        $user_name = $item['firstname']." ".$item['name'];
        print("<p class=\"italic\">Published by ");
        print("<a href=\"mailto:$mail_to\">$user_name</a>");
        print(" at ".$item['posted']."&nbsp;<abbr title=\"Eastern European Time\">EET</abbr>");
        if ( strtotime($item['updated']) > strtotime($item['posted']) ) {
          print(", changed at ".$item['updated']."&nbsp;<abbr title=\"Eastern European Time\">EET</abbr>");
        }
        print("</p>\n");
        print("<div class=\"body\">\n");
        print($item['body']);
        print("</div>\n");
        print("</div>\n\n");
      }
    }
    else {
      if ( isset($news_id) )
        print("<p>No such news.</p>\n");
      elseif ( isset($month) or isset($year) ) {
        print("<p>There are no news from ".get_month($month));
        if ( isset($year) )
          print(", $year.</p>\n");
        else
          print(date('Y')."</p>\n");
      }
      elseif ( isset($q) )
        print("<p>Searched string '$q' didn't match any news.</p>");
      else
        print("<p>News currently not available.</p>\n");
    }
    mysql_free_result($res);
  }
  else
    print("<p>News currently not available.</p>\n");
?>
</div>

<div id="copyright" class="clear">
<hr />
<p>Copyright &copy; 2004-2006 <a href="mailto:gdsotirov@dir.bg">George D. Sotirov</a><br />
All right reserved</p>
</div>

<div id="conformance">
<map id="conformancebar">
<p>
<!-- Valid XHTML 1.0 -->
<a href="http://validator.w3.org/check?uri=referer" hreflang="en">
<img alt="[Valid XHTML 1.0 icon]" height="31" longdesc="http://validator.w3.org/" src="/img/valid-xhtml" title="Valid XHTML 1.0!" width="88" /></a>
<!-- Valid CSS -->
<a href="http://jigsaw.w3.org/css-validator/check/referer" hreflang="en">
<img alt="[Valid CSS icon]" height="31" longdesc="http://jigsaw.w3.org/" src="/img/valid-css" title="Valid CSS!" width="88" /></a>
<!-- Valid Atom 1.0 -->
<a href="http://feedvalidator.org/check.cgi?url=http://<?php echo $_SERVER['SERVER_NAME'] ?>/news/feed&amp;f=atom">
<img alt="[Valid Atom 1.0]" height="31" longdesc="http://feedvalidator.org/" src="/img/valid-atom" title="Validate my Atom feed" width="88" /></a>
<!-- Valid RSS 2.0 -->
<a href="http://feedvalidator.org/check.cgi?url=http://<?php echo $_SERVER['SERVER_NAME'] ?>/news/feed?f=rss&amp;v=2.0">
<img alt="[Valid RSS]" height="31" longdesc="http://feedvalidator.org/" src="/img/valid-rss" title="Validate my RSS feed" width="88" /></a>
<!-- WAI WCAG Conformance -->
<a href="http://www.w3.org/WAI/WCAG1AA-Conformance">
<img alt="[Level Double-A conformance icon]"
height="31" longdesc="http://www.w3.org/WAI/" src="/img/wai-wcag-1.0-2a" title="Explanation of Level Double-A Conformance" width="88" /></a>
<!-- UTF-8 Encoded -->
<a href="http://www.unicode.org/" hreflang="en">
<img alt="[Encoded in UTF-8 icon]" height="31" longdesc="http://www.unicode.org/" src="/img/unicode" title="Encoded in UTF-8!" width="88" /></a>
</p></map>
</div>

<div id="poweredby">
<map id="poweredbybar">
<p><a href="http://www.kernel.org/" hreflang="en">
<img alt="[Powered by Linux]" height="31" longdesc="http://www.kernel.org/" src="/img/linux_pb" title="Powered by Linux" width="88" /></a>
<a href="http://www.apache.org/" hreflang="en">
<img alt="[Powered by Apache]" height="31" longdesc="http://www.apache.org/" src="/img/apache_pb" title="Powered by Apache" width="88" /></a>
<a href="http://www.mysql.com/" hreflang="en">
<img alt="[Works with MySQL]" height="31" longdesc="http://www.mysql.com/" src="/img/mysql_pb" title="Works with MySQL" width="88" /></a>
<a href="http://www.php.net/" hreflang="en">
<img alt="[Powered by PHP]" height="31" longdesc="http://www.php.net/" src="/img/php_pb" title="Powered by PHP" width="88" /></a>
</p></map>
</div>

</body>
<?php
  mysql_close($news_c);
?>
</html>

